[tool.poetry]
name = "fastapi-template"
version = "0.1.0"
description = "Fast API template project, very simple"
authors = ["DominikMarciniszyn <dominik.marciniszyn@codetain.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
