---
version: "3"

tasks:
  build:
    cmds:
      - echo "Building..."
  test:
    cmds:
      - echo "Testing..."
  deploy:
    cmds:
      - echo "Deploying..."
  setupDevEnv:
    desc: Run commands needed to develop application locally
    cmds:
      - poetry install
      - pre-commit install --install-hooks -t pre-commit -t commit-msg
